### ISSUE TITLE
Couldn't run the code

### ISSUE THREAD

**Issue by AlpaslanErdag** [sajithm/text_summarization_lstm_gru#1]
Hi, I couldn't run the code. I'm getting assertation error and .dll errors...
 Can you explain how to run it in mode detail? And what are the prerequisites for it?

**Comment by sajithm** [comment]
Can you provide detailed error message/messages you are seeing?

You would need python 3.7 or greater, tensorflow 2.8 or greater (2.x should be fine, but not tested).
You would also need rouge package (pip install rouge)

You would also need the dataset (link in the README) and the parameters "vocab_path" and "data_dir" set correctly based on the location of the dataset.

**Comment by AlpaslanErdag** [comment]
> Can you provide detailed error message/messages you are seeing?
> 
> You would need python 3.7 or greater, tensorflow 2.8 or greater (2.x should be fine, but not tested). You would also need rouge package (pip install rouge)
> 
> You would also need the dataset (link in the README) and the parameters "vocab_path" and "data_dir" set correctly based on the location of the dataset.

I think I got it, but now I have a different error about log_dir parameter and it's like below.

max_size of vocab was specified as 50000; we now have 50000 words. Stopping reading.
Finished constructing vocabulary of 50000 total words. Last word added: perisic
Creating the batcher ...
Creating the checkpoint manager
Initializing from scratch.
Starting the training ...
Traceback (most recent call last):
  File "text_summarization_lstm_gru/main.py", line 52, in <module>
    main()
  File "text_summarization_lstm_gru/main.py", line 47, in main
    train( params)
  File "/content/text_summarization_lstm_gru/train_test_eval.py", line 40, in train
    train_model(model, b, params, ckpt, ckpt_manager, "{0}/{1}.txt".format(params["log_dir"], model_name))
  File "/content/text_summarization_lstm_gru/training_helper.py", line 40, in train_model
    f = open(out_file,"a+")
FileNotFoundError: [Errno 2] No such file or directory: './log/LSTM_LSTM.txt'

**Comment by sajithm** [comment]
Yes, I will update documentation for this. 
For now, please create a folder "log" in the main folder ("./log" is the default value for the parameter "log_dir"). Or, specify the folder to use with the parameter "log_dir" like --log_dir="/path/to/log/folder"

**Comment by AlpaslanErdag** [comment]
> 

Thanks! But at the and I"ll need this text file right? 
And also I wanted to discuss the based code (https://github.com/steph1793/Pointer_Generator_Summarizer) with you in detail. Do you have LinkedIN account or something to communicate better?

**Comment by sajithm** [comment]
LinkedIn: https://www.linkedin.com/in/sajithm/

**Comment by AlpaslanErdag** [comment]
Hi. Can you share the your rouge results as well? What did you get with 50000 training steps? Thanks! I've tried with 15000 steps and results are bad and for Rouge-2 ; F1 ,precision and recall values returns as 0.
